apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hrms-cluster
  region: us-east-1

nodeGroups:
  - name: hrms-nodes
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    volumeSize: 30
