apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: hrms
type: Opaque
data:
  mysql-root-password: cm9vdA==
  mysql-user: cm9vdA==
  mysql-password: cm9vdA==
  mysql-database: aHJtcw==
